### ISSUE TITLE
Add support for vite v6

### ISSUE THREAD

**Issue by leo3620** [mammadataei/cypress-vite#101]
Hello, vite v6 is now out. Could you please add support to it ? 
<img width="724" alt="image" src="https://github.com/user-attachments/assets/47854f79-1e03-48f1-8eb0-a37796db33ff">

**Comment by ascpixi** [comment]
The last commit was a whole year ago - is this library abandoned? :(

**Comment by mammadataei** [comment]
@ascpixi No, it's not abandoned. I have wanted to publish an update for a while, but unfortunately, I haven't found any free time yet. I'll do my best as soon as I can. In the meantime, PRs are welcome.

**Comment by ascpixi** [comment]
> @ascpixi No, it's not abandoned. I have wanted to publish an update for a while, but unfortunately, I haven't found any free time yet. I'll do my best as soon as I can. In the meantime, PRs are welcome.

Ah, alright - thank you for the response. I tried my hand at creating a version for Vite v6 with no luck - while it does seem to build without errors, it doesn't seem to transpile any code when using it with React + TypeScript (i.e. the index.html still points to `src/main.tsx`, for some reason. Because of deadlines, I had to abandon E2E testing for now in favor of doing only unit testing, though, so I'm afraid I won't continue my efforts to update this plugin.

**Comment by ako-v** [comment]
I added support for version 6 and migrated to es modules, it's just the matter of accepting the PR (#104)

**Comment by Swissbite** [comment]
@mammadataei Any updates on Vite 6 support? I'm currently upgrading from Vite 5 and encountered this issue.

And in the meantime, happy new year :smile:

**Comment by mammadataei** [comment]
In progress.

**Comment by mammadataei** [comment]
released in v1.6.0. resolved by #104.
