### ISSUE TITLE
TypeError: (0 , cypress_vite_1.default) is not a function

### ISSUE THREAD

**Issue by StepanMynarik** [mammadataei/cypress-vite#13]
Hi,

Just installed 1.2.1 in my project.
I'm getting the following error when trying to run 'npx cypress run --e2e'
```
File: cypress.config.ts
---
The error was thrown while executing your e2e.setupNodeEvents() function:
TypeError: (0 , cypress_vite_1.default) is not a function
```

Any idea whats wrong?

**Comment by mammadataei** [comment]
Hi @StepanMynarik, I think this is related to typescript configuration. Try adding `"esModuleInterop": true,` to your tsconfig `compilerOptions`.

**Comment by StepanMynarik** [comment]
Didn't help unfortunately :(
I also tried importing like so ```typescript import * as vitePreprocessor from "cypress-vite";``` but to no avail.

**Comment by emilte** [comment]
I have the same issue

**Comment by emilte** [comment]
> Hi @StepanMynarik, I think this is related to typescript configuration. Try adding `"esModuleInterop": true,` to your tsconfig `compilerOptions`.

Nvm, this seems to have solved it.

**Comment by Robperkstar** [comment]
Hi @StepanMynarik

Not sure if this will help you but I was getting this error along with the error:

`Missing baseUrl in compilerOptions. tsconfig-paths will be skipped`

So I added a baseUrl field to my tsconfig file compilerOptions as: `"baseUrl": "./"` along with ` "esModuleInterop": true,` and this fixed the issue. 

nb. I used `"./"` because my `cypress.config.ts` was on the same folder level as tsconfig.json.
