### ISSUE TITLE
cypress-vite cannot build a SvelteKit app

### ISSUE THREAD

**Issue by wtachau** [mammadataei/cypress-vite#16]
While updating our Svelte app to use SvelteKit, we came across this issue where building our Cypress tests with cypress-vite no longer works correctly— it seems like some of the Vite config options are getting overridden, or not read correctly.

I assume the core issue here is with SvelteKit rather than cypress-vite, but figured a workaround in this library might be possible.

A minimal reproduceable example is available at https://github.com/wtachau/cypress-svelte-kit.

![image](https://user-images.githubusercontent.com/3579673/203386112-27bd997a-aa5e-4a53-a4df-7e5cbfb21b2c.png)

**Comment by mammadataei** [comment]
Hi @wtachau, Thanks for the reproduction.

I think the issue is due to a configuration collision between the `cypress-vite` and `svelte-kit`. It is probably coming from the svelte-kit plugin cause cypress-vite doesn't contain anything specific.

Anyway, I fixed it by creating a separate vite configuration for cypress-vite. 
https://github.com/wtachau/cypress-svelte-kit/pull/1

I hope it solves the problem.
