### ISSUE TITLE
Open PR into official Cypress ecosystem to make this plugin more visible

### ISSUE THREAD

**Issue by JessicaSachs** [mammadataei/cypress-vite#28]
I think the Cypress team would likely appreciate your work in the main repository such that it's more discoverable by users. Either a PR into Cypress's docs mentioning this plugin or a PR adding this repository as an official package would be awesome!

Thoughts?

**Comment by mammadataei** [comment]
@JessicaSachs I think it will be great to make it an official Cypress package If the Cypress team agrees. More people will reach it, and maybe in the future, we can even make it the default preprocessor for Vite projects, like in component testing.

**Comment by JessicaSachs** [comment]
@lmiller11990 and I were chatting on Twitter about this as a possible feature. I think the first step is to get the source code into the monorepo or to get a docs mention. Lachlan do you want to open an issue in the Cy repo?

**Comment by mammadataei** [comment]
Oh, I forgot to mention that it's already listed in the [plugins](https://docs.cypress.io/plugins/directory).

**Comment by lmiller1990** [comment]
Didn't realize this was in the list of plugins already - great!

I think having core support for more than just webpack would be great. A lot of the perceived slowness of Cypress is due to thinks like webpack 4, babel, and various other tooling. I think that an `esbuild-preprocesor` getting built-in would be a better first step, since Vite builds on top of that.

I am not sure how this would fit into existing priorities, but we can definitely open an issue and think about the API, pros/cons, etc. I'd like to see the Cypress monorepo using esbuild (or this) internally, to dogfood it, then we could look to make it a public facing API.

**Comment by mammadataei** [comment]
I used the esbuild with Cypress in my projects before, but because I needed to configure esbuild separately and there was always a gap between the development and testing environments, I decided to use Vite for testing as well. Apart from configuration, the Vite ecosystem and Vite/rollup plugins make the tooling and tests more flexible. For example, in GraphQL projects, I use a rollup plugin for loading the schema automatically. No need to mention that by using Vite, you can also use its specific features like `import. meta` in tests.

I don't know what are your requirements and priorities in Cypress, but from a user perspective, I think since Vite works out of the box without any configuration and it's also easier and more flexible to configure, using a Vite preprocessor might be a better option than esbuild even for non-vite projects.

Anyway, let me know if there is anything I can help with.

**Comment by lmiller1990** [comment]
This makes sense to me.

I don't think we have the bandwidth to investigate adding this to the core repo right now. It's listed in the official plugins. Let's keep an eye on npm downloads, if this number grows enough, that'll indicate a strong desire for this feature, which could help us re-prioritize it.

I will start using it in some personal projects and send some PRs if I run into any bugs!
