### ISSUE TITLE
Compatibility with cucumber preprocessor

### ISSUE THREAD

**Issue by titenis** [mammadataei/cypress-vite#30]
Hello,
Any idea how to run `cypress-vite` with `@badeball/cypress-cucumber-preprocessor`? Having such configuration in cypress config:
```
async function setupNodeEvents(
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions,
): Promise<Cypress.PluginConfigOptions> {
  await CypressCucumberPreProcessor.addCucumberPreprocessorPlugin(on, config);

  on('file:preprocessor', vitePreprocessor());
return config;
}
```
Throws errors when running tests:
```
Oops...we found an error preparing this test file:

  > cypress/e2e/404/404.feature

The error was:

RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
```

It works fine with `@cypress/browserify-preprocessor` and this config:
```
async function setupNodeEvents(
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions,
): Promise<Cypress.PluginConfigOptions> {
  await CypressCucumberPreProcessor.addCucumberPreprocessorPlugin(on, config);

  on(
    'file:preprocessor',
    preprocessor(config, {
      ...browserify.defaultOptions,
      typescript: createRequire(import.meta.url).resolve('typescript'),
    }),
  );
return config;
}

**Comment by mammadataei** [comment]
Hey @titenis,
This issue is not related to the `cypress-vite`. The problem is that Vite doesn't know how to handle `.feature` files. You need a Vite plugin for compiling `.feature` files; something like https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/esbuild.ts.

Unfortunately, I couldn't find a plugin, but I think it's easy to develop one using `@badeball/cypress-cucumber-preprocessor`. 
https://vitejs.dev/guide/api-plugin.html#transforming-custom-file-types

Anyway, let me know if there is anything I can help you with.
