### ISSUE TITLE
Default configuration yields production mode with build

### ISSUE THREAD

**Issue by nuric** [mammadataei/cypress-vite#6]
When I run the tests using `cypress-vite` the default configuration works in production mode rather than development. This is the configuration vite-cypress v1.1.1 builds with

```js
plugins: [
    {
      /* ... */
    },
  ],
  server: { port: 3000 },
  build: {
    target: 'esnext',
    emptyOutDir: false,
    minify: false,
    outDir: '/home/nuric/.config/Cypress/cy/production/projects/project-5de68eb4a828b744154d5b6c5b2f492f/bundles/cypress/support',
    sourcemap: true,
    write: true,
    watch: {},
    lib: {
      entry: '/home/nuric/project/cypress/support/e2e.ts',
      fileName: [Function: fileName],
      formats: [Array],
      name: 'e2e'
    }
  },
  logLevel: 'silent',
  define: { 'process.env.NODE_ENV': '"production"' }
```

I would expect the mode to be set to development which seems to appear in the `configEnv` variable of the plugin. But unless I set the mode explicitly to development in `vite.config.ts` it does not pick it up.

Is there a way to by default build the e2e tests in development mode?

**Comment by mammadataei** [comment]
@nuric, as you've mentioned, the default configuration sets the mode to 'development'. 

https://github.com/mammadataei/cypress-vite/blob/0738fbe8188d2d679982dc2339cc1fbff0c883c7/src/resolveConfig.ts#L11 

I think the `NODE_ENV` is overriding it because this part of the configuration:

https://github.com/mammadataei/cypress-vite/blob/0738fbe8188d2d679982dc2339cc1fbff0c883c7/src/index.ts#L51-L53

I can't remove that part since `vite@^3` does not define the `process.env`, which is necessary for the cypress to work correctly. #2 

I don't know what is changing the `NODE_ENV` to production, but I think [setting `NODE_ENV=development` in your test command](https://github.com/mammadataei/cypress-vite/issues/2#issuecomment-1212091341) would fix the problem without the need to touch `vite.config.ts`.

**Comment by nuric** [comment]
Thank you for your response, I think the interaction between `NODE_ENV` and `vite` is causing this. I also thought by you setting the mode to development it would work but was surprised to see it was still in production. Setting `NODE_ENV=development` is probably the most sensible thing to do for now. Thanks again.

**Comment by MetRonnie** [comment]
I have found setting `process.env.NODE_ENV` in `cypress.config.js` also works
```js
module.exports = defineConfig({
  e2e: {
    setupNodeEvents (on, config) {
      process.env.NODE_ENV = 'development'
      on(
        'file:preprocessor',
        vitePreprocessor(path.resolve(__dirname, './vite.config.js'))
      )
    ...
```
